Make exception from :func:`shutil.copy_directory` readable when a
:exc:`shutil.SameFileError` is raised.
